// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using text_wars;

#nullable disable

namespace text_wars.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("text_wars.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AgilidadeBase")
                        .HasColumnType("REAL");

                    b.Property<double>("ForcaBase")
                        .HasColumnType("REAL");

                    b.Property<string>("NomeClasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VidaBase")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NomeClasse")
                        .IsUnique();

                    b.ToTable("Classe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgilidadeBase = 30.0,
                            ForcaBase = 35.0,
                            NomeClasse = "Guerreiro",
                            VidaBase = 100
                        },
                        new
                        {
                            Id = 2,
                            AgilidadeBase = 50.0,
                            ForcaBase = 20.0,
                            NomeClasse = "Mago",
                            VidaBase = 80
                        });
                });

            modelBuilder.Entity("text_wars.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Jogador");
                });

            modelBuilder.Entity("text_wars.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Agilidade")
                        .HasColumnType("REAL");

                    b.Property<int>("ClasseId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Forca")
                        .HasColumnType("REAL");

                    b.Property<int>("JogadorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VidaAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VidaMaxima")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("JogadorId");

                    b.ToTable("Personagem");
                });

            modelBuilder.Entity("text_wars.Personagem", b =>
                {
                    b.HasOne("text_wars.Classe", "Classe")
                        .WithMany("Personagens")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("text_wars.Jogador", "Jogador")
                        .WithMany("PersonagensJogador")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("text_wars.Classe", b =>
                {
                    b.Navigation("Personagens");
                });

            modelBuilder.Entity("text_wars.Jogador", b =>
                {
                    b.Navigation("PersonagensJogador");
                });
#pragma warning restore 612, 618
        }
    }
}
